# Generated by Django 6.0.3 on 2026-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
