# Generated by Django 6.0.3 on 2026-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_guest_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
