# Generated by Django 6.0.3 on 2026-03-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
