# Generated by Django 6.0.3 on 2026-04-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_roomunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.roomunit'),
        ),
    ]
