# Generated by Django 6.0.3 on 2026-03-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
