# Generated by Django 6.0.3 on 2026-03-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0007_delete_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(default='Hotel', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
