# Generated by Django 6.0.3 on 2026-04-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_task_room_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.roomunit'),
        ),
    ]
