# Generated by Django 6.0.3 on 2026-03-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hote_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.hotel')),
            ],
        ),
    ]
