# Generated by Django 6.0.3 on 2026-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_booking_room_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomunit',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Dirty', 'Dirty'), ('Reserved', 'Reserved'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
