# Generated by Django 6.0.3 on 2026-04-04 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_roomunit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning Supplies'), ('linen', 'Linen & Towels'), ('amenities', 'Guest Amenities'), ('equipment', 'Equipment')], default='cleaning', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='pieces', max_length=50)),
                ('reorder_level', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='Accounts.hotel')),
            ],
        ),
    ]
