# Generated by Django 6.0.3 on 2026-03-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_amenity_hote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='properties',
            field=models.ManyToManyField(blank=True, to='Accounts.amenity'),
        ),
    ]
