# Generated by Django 6.0.3 on 2026-04-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_inventoryitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='created_at',
            new_name='assigned_date',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory', to='Accounts.staff'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='Accounts.roomunit'),
        ),
    ]
