# Generated by Django 6.0.3 on 2026-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
