# Generated by Django 5.2.7 on 2026-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_hotel_is_subscribed_alter_amenity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
