# Generated by Django 5.2.7 on 2026-04-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_amenity_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='is_default',
        ),
        migrations.AddField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('default', 'Default'), ('premium', 'Premium')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
