# Generated by Django 6.0.3 on 2026-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_booking_created_by_inventoryitem_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('staff', 'date')},
        ),
    ]
