# Generated by Django 5.2.7 on 2026-04-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
