# Generated by Django 6.0.3 on 2026-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_delete_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='task',
            name='staff',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
